image:
  #change repository
  repository: docker.io/gopalvithaljayanthi/nginx
  tag: mybranch-1275

service:
  type: NodePort
ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

